title: Ultimate Media
nav:
  stuff:
    - name: C1200 Games
      image: /assets/unsplash-game.jpg
      link: /stuff/c1200-games
    - name: CoolStuff
      image: /assets/unsplash-news.jpg
      link: /stuff/coolstuff
    - name: ChatSurf
      image: /assets/unsplash-surf.jpg
      link: /stuff/chatsurf
    - name: goum.cf
      image: /assets/unsplash-phone.jpg
      link: /stuff/goum-cf
    - name: Aviation Edits Website
      image: /assets/unsplash-plane.jpg
      link: https://aviationedits.goum.cf
